carts/urls.py
from django.urls import path, include

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view,
        customer_info,
        payment,
        payment_canceled
        )

app_name = 'carts'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('customer_info/', customer_info, name='customer_info'),
    path('process-payment/<str:order_id>/', payment, name='payment'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
    path('checkout/success/', checkout_done_view, name='success'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from .views import homepage, contact

urlpatterns = [

]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import login_page, register_page, guest_register_view
from carts.views import cart_home, cart_update, checkout_done_view
from events.views import register_to_event
from blogs.views import blog_list, blog_detail
# from partners.views import partners_list
from .views import homepage, contact, about, logout_request, terms
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from vendors.views import vendors_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name = "homepage"),
    path('login/', login_page, name = "login_page"),
    path("logout/", logout_request, name="logout"),
    path('register/guest', guest_register_view, name = "guest_register"),
    path('register/', register_page, name = "register_page"),
    path('contact/', contact, name = "contact"),
    path('about/', about, name="about"),
    path('cart/customer_info/terms', terms, name="terms"),
    path('products/', include("products.urls")),
    path('cart/', include('carts.urls')),
    path('events/', include('events.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('blog/', blog_list, name="blog_list"),
    path('blog/<int:blog_id>', blog_detail, name='blog_detail'),
    path('vendors/', vendors_list, name="vendors_list"),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('checkout/success/', checkout_done_view, name='success'),



    # path('cart/', cart_home, name='cart'),
    # path('cart/update', cart_update, name='update'),


    # path('featured/', ProductFeaturedListView.as_view()),
    # path('featured/<pk>/', ProductFeaturedDetailView.as_view()),
    # path('products/<slug>/', ProductDetailSlugView.as_view()),
    # path('products/', ProductListView.as_view()),
    # path('products-fbv/', product_list_view, name='product_list_view'),
    # # path('products/<pk>/', ProductDetailView.as_view()),
    # path('products-fbv/<pk>/', product_detail_view),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/models.py
from decimal import Decimal
from django_pandas.io import *

from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product

User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        # print(user)
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)



class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True,on_delete=models.CASCADE)
    products    = models.ManyToManyField(Product, blank=True)
    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

#FOLLOWING CHANGE
#ADDED THIS MODEL THAT IS GOING TO STORE PRODUCT QUANTITIES
#FOR THIS I HAVE ALSO STOPPED THE SIGNALS YOU HAVE USED BY
#COMMENTING THEM OUT
class CartItems(models.Model):
    product = models.ForeignKey(Product, null=True, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, null=True, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    quantity_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)

    def __str__(self):
        return str(self.cart)
    #CALCULATE ON RUNTIME EACH PRODUCT PRICE W.R.T QUANTITY
    def get_total(self):
        return self.product.price * self.quantity

    #STORING EACH PRODUCT PRICE W.R.T QUANTITY
    def save(self, *args, **kwargs):
        quantity_total = Decimal(float(self.product.price) * float(self.quantity))
        self.quantity_total = quantity_total
        super(CartItems, self).save(*args, **kwargs)


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

# ~ m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) # * Decimal(1.08)  8% tax
    else:
        instance.total = 0.00

#pre_save.connect(pre_save_cart_receiver, sender=Cart)

carts/views.py
from decimal import Decimal
import pandas as pd
from paypal.standard.forms import PayPalPaymentsForm
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.conf import settings
from django_pandas.io import *
from django.core.mail import send_mail
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from .models import Cart, Product, CartItems
from addresses.models import Address
from orders.models import Order
from accounts.forms import LoginForm, GuestForm
from billing.models import BillingProfile
from accounts.models import GuestEmail
from addresses.forms import AddressForm
from ordersweb.models import OrderWeb
from ordersweb.forms import OrderWebForm





# def cart_create(user=None):
#     cart_obj = Cart.objects.create(user=None)
#     print('New Cart created')
#     return cart_obj

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    #FOLLOWING CHANGE
    #TO DISPLAY THE CART VALUES QUANTITY WISE
    #WITH CALCULATED TOTAL
    item_obj = CartItems.objects.filter(cart=cart_obj)
    total = 0
    # df = read_frame(item_obj, fieldnames=['product', 'quantity', 'quantity_total'])
    # print(df)
    for item in item_obj:
        # print(item.product, item.quantity,item.get_total()
        total += item.get_total()

    cart_obj.total=total
    cart_obj.save()
    return render(request, "carts/home.html", {"cart": cart_obj, "items": item_obj, "total": total})

def cart_update(request):
    product_id = request.POST.get('product_id')
    #FOLLOWING CHANGE
    #TOOK THE QUANTITY VALUE FROM FORM POST VALUES
    number = request.POST.get('number')
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if 'remove' in request.POST:
            item = CartItems.objects.get(product_id=product_id,cart=cart_obj)
            item.delete()
            cart_obj.products.remove(product_obj)
        else:

            #IF THE ITEM ALREADY EXIST UPDATE ITS QUANTITY
            #ELSE CREATE THE NEW OBJECT WITH ASSIGNED QUANTITY
            try:
                item = CartItems.objects.get(product=product_obj,cart=cart_obj)
                item.quantity = number
                item.save()
            except:
                item = CartItems.objects.create(product=product_obj,cart=cart_obj, quantity=number)
                cart_obj.products.add(product_obj) # cart_obj.products.add(product_id)


        request.session['cart_items'] = cart_obj.products.count()
        # return redirect(product_obj.get_absolute_url())
    return redirect("carts:home")

def customer_info(request):
    form = OrderWebForm()
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    item_obj = CartItems.objects.filter(cart=cart_obj)

    # for item in item_obj:
    #     print(item.product, item.quantity,item.get_total())
    df = read_frame(item_obj, fieldnames=['product', 'quantity', 'quantity_total'])
    print(df)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")
    else:
        order_obj, new_order_obj = Order.objects.get_or_create(cart=cart_obj)

    if request.method == "POST":
                id = cart_obj.id
                first_name = request.POST["first_name"]
                last_name = request.POST["last_name"]
                email = request.POST["email"]
                phone_number = request.POST["phone_number"]
                address_line_1 = request.POST["address_line_1"]
                # address_line_2 = request.POST["address_line_2"]
                city = request.POST["city"]
                country = request.POST["country"]
                postal_code = request.POST["postal_code"]
                cart =  Cart.objects.get(id=id)
                order_cost      = cart_obj.total
                delivery_method = request.POST["delivery_method"]
                #save to db
                order_web = OrderWeb(first_name=first_name, last_name=last_name, email=email, phone_number = phone_number,
                                    address_line_1=address_line_1,city=city,postal_code=postal_code, cart=cart, order_cost=order_cost,
                                    delivery_method= delivery_method)
                order_web.save()

                print(df)
                #email alert
                subject = 'הזמנה חדשה מאתר הסבים שותים'

                alert_message = "{alert_fname}\n{alert_lname}\n{alert_eaddress}\n{alert_tel}\n{alert_address}\n{alert_delivery_method}\n\n{order_details}".format(
                        alert_fname = "שם פרטי: " + first_name,
                        alert_lname = "שם משפחה: " + last_name,
                        alert_eaddress = "אימייל: " + email,
                        alert_tel = "טלפון: " + phone_number,
                        alert_address= "כתובת: " + address_line_1 + " " +", " + city + ", " + country + " " + postal_code,
                        alert_delivery_method = "צורת אספקה: " + delivery_method,
                        order_details = df,


                    )
                from_email = settings.EMAIL_HOST_USER
                to_list_alert = ['rabbi.shani@gmail.com', 'info@hasabimshotim.com']
                send_mail(subject, alert_message, from_email, to_list_alert, fail_silently = True)

                #empty the cart
                request.session['cart_items'] = 0
                del request.session['cart_id']
                return redirect("carts:success")
    return render(request, "carts/customer_info.html", {"object": order_obj, 'form': form })

###### relevant for authentication and payment ######

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None

    if cart_created or cart_obj.products.count() == 0:
        return redirect("carts:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id)
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()


    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            # order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("carts:payment", order_id=order_obj.order_id)
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
    }

    return render(request, "carts/checkout.html", context)

def payment(request, order_id):
    order = get_object_or_404(Order, order_id=str(order_id))
    host = request.get_host()

    paypal_dict = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': str(order.total),
        'item_name': 'Order {}'.format(order.id),
        'invoice': str(order.id),
        'currency_code': 'USD',
        'notify_url': 'http://{}{}'.format(host,
                                           reverse('paypal-ipn')),
        'return_url': 'http://{}{}'.format(host,
                                           reverse('success')),
        "currency_code": "ILS",
        # 'cancel_return': 'http://{}{}'.format(host, reverse('payment_cancelled')),
    }

    form = PayPalPaymentsForm(initial=paypal_dict)
    if form.is_valid():
        form.save()
        order.mark_paid()
    return render(request, 'carts/payment.html', {'order': order, 'form': form})



@csrf_exempt
def payment_canceled(request):
    return render(request, 'carts/cancelled.html')


def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})

carts/templates/carts/cancelled.html
{% extends 'base.html' %}
 
{% block content %}
 
    <p>Payment cancelled.</p>
 
{% endblock %

carts/templates/carts/checkout-done.html
{% extends "base.html" %}


{% block content %}
<div class="site-section mt-5">
  <div class="container">
      <div class='col-6 mx-auto py-5 text-center'>
      <h1 class='rtl-center'>הזמנתך התקבלה</h1>
      <h1 class='rtl-center'>אנו ניצור איתך קשר בהקדם</h1>
      <h1 class='rtl-center'>תודה!</h1>
      <a href="{% url 'homepage' %}" class="btn btn-md height-auto px-4 py-3 btn-primary rtl">לחזרה לעמוד הבית</a>

      </div>
  </div>
</div>

{% endblock %}

carts/templates/carts/checkout.html
{% extends "base.html" %}


{% block content %}
{% if not billing_profile %}

<div class="site-section mt-5">
  <div class="container">

    <div class='row text-center'>
      <div class='col-12 col-md-6 rtl'>
            <p class='lead rtl'>התחבר</p>
            {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
        </div>

        <div class='col-12 col-md-6 rtl'>
            <p class='lead rtl'>המשך כאורח</p>

            {% url "guest_register" as guest_register_url %}
            {% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url %}
        </div>
    </div>
  </div>
</div>

    {% else %}

            {% if not object.shipping_address %}
    <div class="site-section mt-5">
        <div class="container">
              <div class='row text-center'>
                <div class='col-12'>
                    <p class='lead rtl'>כתובת למשלוח</p>
                    <hr/>
                </div>
                <div class='col-12 rtl'>
                        {% url "checkout_address_create" as checkout_address_create %}
                        {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
                 </div>
                <div class='col-12 rtl'>
                        {% url 'checkout_address_reuse' as checkout_address_reuse %}
                        {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}
                </div>
            </div>
        </div>
  </div>


            {% elif not object.billing_address %}
      <div class="site-section mt-5">
          <div class="container">
              <div class='row text-center'>
                <div class='col-12'>
                     <p class='lead rtl'>כתובת חיוב</p>
                    <hr/>
                </div>
                <div class='col-12 rtl'>
                {% url "checkout_address_create" as checkout_address_create %}
                {% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}
                </div>
                  <div class='col-12 rtl'>
                    {% url 'checkout_address_reuse' as checkout_address_reuse %}
                    {% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri  address_type='billing' action_url=checkout_address_reuse %}
             </div>
           </div>
        </div>
    </div>

            {% else %}
            <div class="site-section mt-5">
                <div class="container">
                    <div class='row text-center'>
                      <div class='col-12'>
                           <p class='lead rtl'>סיכום הזמנה</p>
                          <hr/>
                <p class = "rtl"> מוצרים: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                <p class = "rtl"> כתובת למשלוח: {{ object.shipping_address.get_address }}</p>
                <p class = "rtl"> כתובת חיוב: {{ object.shipping_address.get_address }}</p>
                <p class = "rtl"> סכום ביניים לתשלום: {{ object.cart.total }}</p>
                <p class = "rtl"> דמי משלוח: {{ object.shipping_total }}</p>
                <p class = "rtl"> סה"כ לתשלום כולל משלוח: {{ object.total }}</p>

              <form class='form' method='POST' action="">{% csrf_token %}
                  <button type='submit' class='btn btn-md height-auto px-4 py-3 btn-primary rtl'>למעבר לתשלום</button>
              </form>

                  <!-- <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                  <input type="hidden" name="cmd" value="_s-xclick">
                  <input type="hidden" name="hosted_button_id" value="NW7HYLZYLPTHL">
                  <input type="image" src="https://www.paypalobjects.com/he_IL/i/btn/btn_buynow_LG.gif" border="0" name="submit" alt="PayPal - הדרך הקלה והבטוחה יותר לשלם באינטרנט!">
                  <img alt="" border="0" src="https://www.paypalobjects.com/he_IL/i/scr/pixel.gif" width="1" height="1">
                  </form> -->


                {% endif %}
          <!-- <div class="site-section">
            <div class="container">
              <div class="row">
                <div class="col-lg-12 single-content">
                      <h1 class ="rtl">סיכום הזמנה</h1>

                      <table class="table col-lg-12 single-content rtl">
                        <tbody>
                          <tr>
                            <td> סה"כ סל הקניות: {{ object.cart.total }} ש"ח </td>
                          </tr>

                            <tr>
                              <td> דמי משלוח: {{ object.shipping_total }} ש"ח </td>
                            </tr>

                            <tr>
                              <td> סה"כ לתשלום: {{ object.total }} ש"ח </td>
                            </tr>

                        </tbody>
                      </table>

                      </div>
                    </div>
                  </div>
              </div> -->

          {% endif %}

</div>
</div>
{% endblock %}

carts/templates/carts/customer_info.html
{% extends "base.html" %}


{% block content %}


<div class="site-section mt-5">
    <div class="container">
        <div class='row text-center'>
            <div class='col-12'>
               <p class='lead rtl'>אנא השאר פרטים ואנו ניצור איתך קשר לצורך השלמת ההזמנה </p>

                <p class = "rtl"> סה"כ סכום הזמנה (לא כולל משלוח): {{object.cart.total}} ש"ח</p>

                <form name="form" method="post">
                  {% csrf_token %}
                  <div class="row rtl">
                      <div class="col-md-6 form-group">
                          {% for field in form %}
                            <label>  {{field.label_tag}} </label>
                            {{field}}
                          {% endfor %}
                          <br>
                          <br>

                          <input type="submit" value="שלח הזמנה" class="btn btn-primary py-3 px-5 btndir center">
                    </div>
                  </div>
                </form>

          </div>
        </div>
    </div>
</div>

{% endblock %}

carts/templates/carts/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 single-content">

                <h1 class ="rtl">עגלה</h1>

                {% if cart.products.exists %}
                <table class="table col-lg-12 single-content rtl">
                  <thead>
                    <tr>
                      <th>#</th>
                      <th>שם המוצר</th>
                      <th>כמות</th>
                      <th>מחיר</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in items %}
                    <tr>
                      <th scope="row">{{ forloop.counter }}</th>
                      <td><a href='/products/{{item.product.slug}}/?quantity={{item.quantity}}'>{{ item.product.title }} {{ item.product.year }}, {{ item.product.vendor}}</a>

                        {% include 'products/snippets/update-cart.html' with product=item.product cart=item.cart in_cart=True %}
                      </td>
                      <td>{{item.quantity}}</td>
                      <td>{{item.get_total}} ש"ח</td>
                    </tr>
                    {% endfor %}
                    <tr>
                      <td></td>
                      <td><b>סה"כ </b></td>
                      <td></td>
                      <td>{{total}} ש"ח</td>
                    </tr>

                    <tr>
                      <td colspan="2"></td>
                      <td><a class='btn btn-md height-auto px-4 py-3 btn-primary rtl' href='{% url "carts:customer_info" %}'>להשלמת ההזמנה</a></td>
                      <td></td>
                    </tr>
                  </tbody>
                </table>

                {% else %}
                <p class='lead rtl'>עוד לא הוספת מוצרים לעגלה.</p>
                <p class='lead rtl'>זקוק לעזרה? <a href="{% url 'contact' %}" class="">צור קשר</a></p>
                <p class = "rtl"><a href="{% url 'products' %}" class="btn btn-md height-auto px-4 py-3 btn-primary rtl">חזור לחנות</a></p>
                {% endif %}

              </div>
          </div>
        </div>
     </div>

{% endblock %}

carts/templates/carts/payment.html
{% extends 'base.html' %}

{% block title %}תשלום{% endblock %}

{% block content %}


    <div class="site-section mt-5">
      <div class="container">
          <div class='rtl-center'>
            <!-- <h2 class ="rtl-center"> לבחירתך שתי אפשרויות לביצוע תשלום והשלמת ההזמנה</h2>
            <br>
                <h4 class = "rtl-center">תשלום עם PayPal</h4>
                    {{ form.render }}
                    <hr> -->
                <a class="px-3 py-2 btn-primary rtl" href="/">השאר פרטים ואנו נחזור אליך טלפונית להשלמת ההזמנה</a>
            </div>
          </div>
      </div>
{% endblock %}