carts/urls.py
from django.urls import path, include

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view,
        customer_info,
        payment,
        payment_canceled
        )

app_name = 'carts'

urlpatterns = [
    path('', cart_home, name='home'),
    path('update/', cart_update, name='update'),
    path('checkout/', checkout_home, name='checkout'),
    path('customer_info/', customer_info, name='customer_info'),
    path('process-payment/<str:order_id>/', payment, name='payment'),
    path('payment-cancelled/', payment_canceled, name='payment_cancelled'),
    path('checkout/success/', checkout_done_view, name='success'),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from .views import homepage, contact

urlpatterns = [

]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import login_page, register_page, guest_register_view
from carts.views import cart_home, cart_update, checkout_done_view
from events.views import register_to_event
from blogs.views import blog_list, blog_detail
# from partners.views import partners_list
from .views import homepage, contact, about, logout_request, terms
from addresses.views import checkout_address_create_view, checkout_address_reuse_view
from vendors.views import vendors_list

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage, name = "homepage"),
    path('login/', login_page, name = "login_page"),
    path("logout/", logout_request, name="logout"),
    path('register/guest', guest_register_view, name = "guest_register"),
    path('register/', register_page, name = "register_page"),
    path('contact/', contact, name = "contact"),
    path('about/', about, name="about"),
    path('cart/customer_info/terms', terms, name="terms"),
    path('products/', include("products.urls")),
    path('cart/', include('carts.urls')),
    path('events/', include('events.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('blog/', blog_list, name="blog_list"),
    path('blog/<int:blog_id>', blog_detail, name='blog_detail'),
    path('vendors/', vendors_list, name="vendors_list"),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('checkout/success/', checkout_done_view, name='success'),



    # path('cart/', cart_home, name='cart'),
    # path('cart/update', cart_update, name='update'),


    # path('featured/', ProductFeaturedListView.as_view()),
    # path('featured/<pk>/', ProductFeaturedDetailView.as_view()),
    # path('products/<slug>/', ProductDetailSlugView.as_view()),
    # path('products/', ProductListView.as_view()),
    # path('products-fbv/', product_list_view, name='product_list_view'),
    # # path('products/<pk>/', ProductDetailView.as_view()),
    # path('products-fbv/<pk>/', product_detail_view),

]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path, include

from .views import (
        events_list,
        event_detail,
        register_to_event,
        thank_you,
        )

app_name = 'events'

urlpatterns = [
    path('', events_list, name='home'),
    path('list/thank_you', thank_you, name='thank_you'),
    path('list/register_to_event', register_to_event, name='register_to_event'),
    path('list/<int:event_id>', event_detail, name='details'),


]

templates/about.html
{% extends 'base.html' %}

{% load static %}


{% block content %}
    <div class="hero-2" style="background-image: url({% static 'images/clear-long-stemmed-wine-glass-39605.jpg'%})";>
     <div class="container">
        <div class="row justify-content-center text-center align-items-center">
          <div class="col-md-8">
            <h2>עלינו</h2>
            <!-- <span class="sub-title">הסבים שותים מציעה מגוון יינות ומשקאות אלכוהולים איכותים במחירים אטרקטיבים</span> -->
          </div>
        </div>
      </div>
    </div>

    <div class="site-section py-5 custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6">
            <div class="block-16">
              <figure>
                <img src="{% static 'images/IMG_6955.JPG' %}" alt="Image placeholder" class="img-fluid ">
              </figure>
            </div>
          </div>
          <div class="col-md-1"></div>
          <div class="col-md-5">

            <div class="site-section-heading pt-3" style ="padding-bottom: 0px">
              <h2 class="text-black font-heading-serif rtl">מי אנחנו</h2>
            </div>
<p class = "rtl">"הסבים שותים" הוא מחסן קטן ליינות ולמוצרים אזוריים הנמצא בצור הדסה. לחנות חזון לשווק מוצרי בוטיק המיוצרים באזור בכמות מדודה וביחס אוהב. לדאבוננו למוצרים נפלאים אלה אין חשיפה בחנויות הקיימות לכן המחסן מעוניין לסייע בחשיפתם לפני הציבור ולהעניק לתושבי האזור ולאורחים אפשרות ליהנות מהכרות ובעיקר את ההנאה שבגילוי באיכויות ובייחודו של האזור.
כשלושת אלפי שנה אזור זה מיושב ומעניק את סגולותיו לתושביו בתחום הרוח כמו בתחום החקלאי. גולת הכותרת של הגידול החקלאי באזור הם הכרמים המעטרים את מדרונות הגבעות והמניבים ענבים למאכל וליינות. התושבים ששבו למקום גילו מחדש את קסם הפקת היין הם פיתחו תחומים חדשים ושיפרו את הקיימים.</p>

            <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Delectus consequuntur hic quaerat cupiditate tempore temporibus nulla at eum!</p> -->
          </div>
        </div>
      </div>
    </div>



    <div class="site-section bg-light custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row">
          <div class="col-md-6 order-md-2">
            <div class="block-16">
              <figure>
                <img src="{% static 'images/amir_img.JPG' %}" alt="Image placeholder" class="img-fluid ">
              </figure>
            </div>
          </div>
          <div class="col-md-5 mr-auto rtl">


            <div class="site-section-heading pt-3 mb-4 rtl">
              <h2 class="text-black font-heading-serif rtl">ללמוד להכיר את היין</h2>
            </div>
            <p class="rtl">אמיר עוסק בחינוך יותר משלושים שנה ומאמין שגם ליהנות מיין צריך ללמוד. הרצון להיות חלק מהעשייה והמחשבה שיש לו גם מעט לתרום בנושא גמלו בלבו את החלטה להיכנס לתחום.
            המחסן מחפש לסייע לבעלי רעיונות ועסקים קטנים נוספים בראשית דרכם להגשים את חלומם ולהביא את עמל כפיהם למדפי המחסן.</p>

          </div>
        </div>
      </div>
    </div>

    <div class="site-section py-5 custom-border-bottom" data-aos="fade">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-6">
            <div class="block-16">
              <figure>
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3393.937801289946!2d35.102461999999996!3d31.717594000000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1502db06430280b7%3A0x92441b24f2e8e39e!2z15TXodeR15nXnSDXqdeV16rXmded!5e0!3m2!1siw!2sil!4v1580785311878!5m2!1siw!2sil" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>

              </figure>
            </div>
          </div>
          <div class="col-md-1"></div>
          <div class="col-md-5">

            <p class = "rtl" style ="margin-top: 80px;">
              <h4 class = "rtl">שעות פתיחה:</h4>
              <p class = "rtl" style="margin-bottom: 40px;">
                ימים א-ג ו-ה' בין 16:30-19:00
                  <br>
                יום ו' וערבי חג בין 10:30-13:00
                <br>
                </p>
              <h4 class = "rtl">דרכי הגעה:</h4>
              <p class = "rtl">
              מכביש 375 נכנסים בכניסה המזרחית של צור הדסה לשד' הרי יהודה. במעגל התנועה הראשון עולים לכיוון שכונה הותיקה ברח' יסמין. מצד ימין עשרים וחמישה מטרים מעל מעגל התנועה יש שלט המכוון למרתף.
            </p>
          </div>
        </div>
      </div>
    </div>


<!--  תמיכה, שילוח וכדו  -->
    <!-- <div class="site-section site-section-sm site-blocks-1 border-0" data-aos="fade">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="">
            <div class="icon mr-4 align-self-start">
              <span class="icon-truck text-primary"></span>
            </div>
            <div class="text">
              <h2 class="font-heading-serif">Free Shipping</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan
                tincidunt fringilla.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="100">
            <div class="icon mr-4 align-self-start">
              <span class="icon-refresh2 text-primary"></span>
            </div>
            <div class="text">
              <h2 class="font-heading-serif">Free Returns</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan
                tincidunt fringilla.</p>
            </div>
          </div>
          <div class="col-md-6 col-lg-4 d-lg-flex mb-4 mb-lg-0 pl-4" data-aos="fade-up" data-aos-delay="200">
            <div class="icon mr-4 align-self-start">
              <span class="icon-help text-primary"></span>
            </div>
            <div class="text">
              <h2 class="font-heading-serif">Customer Support</h2>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus at iaculis quam. Integer accumsan
                tincidunt fringilla.</p>
            </div>
          </div>
        </div>
      </div>
    </div> -->

    <div class="site-section bg-light">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 section-title text-center mb-5">
            <h2 class="d-block">לקוחות ממליצים</h2>
            <div class="owl-carousel owl-slide-3 owl-slide">
                <blockquote class="testimony">
                  <img src="{% static 'images/tamar_dash.png' %}" alt="Image">
                  <p class="rtl">&ldquo;מקום קסום. לא רק יינות מעולים במחירים לכל כיס. לא רק מגוון ייחודי של יינות אזוריים (ועוד משקאות מפתיעים) אלא גם שירות, יחס וסיפורים הממלאים את הכוס ואת הלב
                                        מומלץ מומלץ מומלץ.
                                        צריך להוסיף את המקום הזה לכל מדריך מטיילים.
                                        המלצה משפחתית! ( כי את הילדים מפנקים בבייגלה)&rdquo;</p>
                  <p class="small text-primary"> תמר דשבסקי </p>
                </blockquote>
                <blockquote class="testimony">
                  <img src="{% static 'images/david_img.JPG' %}" alt="Image">
                  <p class = "rtl">&ldquo;'הסבים שותים' הוא לא רק מקום שבו ניתן לרכוש יינות נבחרים מיקבי האיזור. אני אוהב להגיע ל'הסבים שותים' כדי לפגוש עוד אנשים שכמוני יודעים להעריך יין טוב ותמיד במחירים נוחים שלא פוגמים בחווית הקניה. אמיר ישמח לסייע לכול מי שצריך קצת עזרה והכוונה בהתאמת היין לארוע. שווה לבקש סקירה על הבירות האיזוריות ועל המשקאות האלכוהוליים שמשלימים את הצע המוצרים שבמרתף.&rdquo;</p>
                  <p class="small text-primary">דוד טובל</p>
                </blockquote>
                <blockquote class="testimony">
                  <img src="{% static 'images/efrat_img.jpg' %}" alt="Image">
                  <p class = "rtl">&ldquo;אני מכירה את 'הסבים שותים' מיום הפתיחה של המקום. אוירה נעימה שרות מסור וסבלני. מבחר המוצרים מגוון ואיכותי. לא פעם נעזרנו במקום כאשר הינו זקוקים ברגע האחרון ליין או למתנה מכובדת ומיוחדת. ממליצה לבקר במקום ולהתרשם&rdquo;</p>
                  <p class="small text-primary">אפרת ורדי</p>
                </blockquote>
                <!-- <blockquote class="testimony">
                  <img src="{% static 'images/person_1.jpg' %}" alt="Image">
                  <p>&ldquo;Lorem ipsum dolor sit amet, consectetur adipisicing elit. Libero sapiente beatae, nemo quasi quo neque consequatur rem porro reprehenderit, a dignissimos unde ut enim fugiat deleniti quae placeat in cumque?&rdquo;</p>
                  <p class="small text-primary">&mdash; Allie Smith</p>
                </blockquote> -->
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/base.html
{% url 'homepage' as home_url %}
{% url 'about' as about_url %}
{% url 'blog_list' as blog_url %}
{% url 'events:home' as events_url %}
{% url 'vendors_list' as vendors_url %}
{% url 'products' as products_list_url %}
{% url 'contact' as contact_url %}
{% url 'login_page' as login_url %}
{% url 'logout' as logout %}
{% url 'register_page' as register_url %}
{% url 'cart:home' as cart_url %}


{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <title>הסבים שותים</title>
  <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" />

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Cinzel:400,700|Montserrat:400,700|Roboto&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Heebo">
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link href="{% static 'css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' />

  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.css" />


  <style>
  .rtl {
          direction: rtl !important;
          text-align: right;
          font-family: "Heebo", regular;
    }
    .rtl-center {
            direction: rtl !important;
            text-align: center;
            font-family: "Heebo", regular;
          }
  .font-montserrat{
          font-family: "Heebo", regular;
    }
  .img-width {
        max-width: 50% !important;

  .nav-rtl {
        direction: rtl !important; /* Add direction for menu */
    }

  </style>

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target rtl">
      <div class="site-mobile-menu-header rtl">
        <div class="site-mobile-menu-close mt-3 rtl">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body rtl"></div>
    </div>



    <div class="header-top">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 text-center">
            <a href="{% url 'homepage' %}" class="site-logo">
              <img src="{% static 'images/hasabim_shotim_logo_v3_final_web_size.png' %}" alt="Image" class="img-fluid img-width">
            </a>
          </div>
          <a href="#" class="mx-auto d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black "><span class="icon-menu h3"></span></a>
        </div>
      </div>



      <div class="site-navbar py-2 js-sticky-header site-navbar-target d-none pl-0 d-lg-block rtl" role="banner">
      <div class="container">
          <div class="d-flex align-items-center">
            <div class="mx-auto">
              <nav class="site-navigation position-relative text-left" role="navigation">
                <ul class="site-menu main-menu js-clone-nav mx-auto d-none pl-0 d-lg-block border-none nav-rtl" style ="padding-right: 0px">
                  <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                      <a href="{% url 'homepage' %}" class="nav-link">בית</a>
                  </li>
                  <li class="nav-item {% if request.path == about_url %}active{% endif %}">
                      <a href="{% url 'about' %}" class="nav-link">עלינו</a>
                  </li>
                  <li class="nav-item {% if request.path == vendors_url %}active{% endif %}">
                      <a href="{% url 'vendors_list' %}" class="nav-link">יצרנים</a>
                  </li>
                  <li class="nav-item {% if request.path == events_url %}active{% endif %}">
                      <a href="{% url 'events:home' %}" class="nav-link">פעילויות</a>
                  </li>
                  <li class="nav-item {% if request.path == blog_url %}active{% endif %}">
                      <a href="{% url 'blog_list' %}" class="nav-link">בלוג</a>
                  </li>
                  <li class="nav-item {% if request.path == products_list_url %}active{% endif %}">
                      <a href="{% url 'products' %}" class="nav-link">חנות</a>
                  </li>
                  <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                      <a href="{% url 'contact' %}" class="nav-link">צור קשר</a>
                  </li>

                  <li>
                    |
                  </li>

                  {% if request.user.is_authenticated %}
                   <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
                     <a class="nav-link" href="{% url 'logout' %}">שלום {{user.username}}, התנתק </a>

                  </li>
                  {% else %}
                   <!-- <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                    <a class="nav-link" href="{{ register_url }}">הרשמה</a>
                  </li>
                  <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                    <a class="nav-link" href="{{ login_url }}">התחבר</a>
                  </li> -->
                  {% endif %}

                  <li>
                   <a class="nav-link" href="{% url 'carts:home' %}"> עגלה <i class="fa fa-shopping-cart" aria-hidden="true"></i>    {{ request.session.cart_items }}</a>
                 </li>

                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>




{% block content %}


{% endblock %}



<div class="footer">
  <div class="container">

    <div class="row">
      <div class="col-12 text-center">
        <div class="social-icons">
          <a href="https://www.facebook.com/pg/HasbimShotim"><span class="icon-facebook"></span></a>
          <a href="https://www.instegram.com/hasabimshotim"><span class="icon-instagram"></span></a>
          <a href="tel:+972-54-4874898"><span class="icon-phone"></span></a>
          <a href="mailto:amiranita@gmail.com"><span class="icon-envelope"></span></a>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div class="copyright">
            <p>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>



        </div>
      </div>
    </div>
  </div>
</div>


</div>
<!-- .site-wrap -->


<!-- loader -->
<div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#ff5e15"/></svg></div>

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/jquery.mb.YTPlayer.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/cookieconsent@3/build/cookieconsent.min.js" data-cfasync="false"></script>

<script>
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#930077",
      "text": "#fff"
    },
    "button": {
      "background": "#930077",
      "border": "#fff",
      "text": "#fff"
    }
  },
  "position": "bottom-left",
  "content": {
    "message": "אתר זה משתמש בעוגיות דפדפן. אנו משתמשים בעוגיות כדי לספק לך את חווית השימוש הטובה ביותר באתרנו.",
    "dismiss": "הבנתי, תודה",
    "link": "למד עוד"
  }
});

</script>
</body>

</html>